// Generated by gencpp from file darknet_ros_msgs/distances.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_DISTANCES_H
#define DARKNET_ROS_MSGS_MESSAGE_DISTANCES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <distance.h>

namespace darknet_ros_msgs
{
template <class ContainerAllocator>
struct distances_
{
  typedef distances_<ContainerAllocator> Type;

  distances_()
    : header()
    , distances()  {
    }
  distances_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distances(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::darknet_ros_msgs::distance_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::darknet_ros_msgs::distance_<ContainerAllocator> >::other >  _distances_type;
  _distances_type distances;





  typedef boost::shared_ptr< ::darknet_ros_msgs::distances_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_msgs::distances_<ContainerAllocator> const> ConstPtr;

}; // struct distances_

typedef ::darknet_ros_msgs::distances_<std::allocator<void> > distances;

typedef boost::shared_ptr< ::darknet_ros_msgs::distances > distancesPtr;
typedef boost::shared_ptr< ::darknet_ros_msgs::distances const> distancesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_msgs::distances_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_msgs::distances_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace darknet_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'darknet_ros_msgs': ['/home/zhao/Data/Function/ROS_yolov3-coordinate/src/darknet_ros/darknet_ros_msgs/msg', '/home/zhao/Data/Function/ROS_yolov3-coordinate/devel/share/darknet_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::distances_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::distances_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::distances_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::distances_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::distances_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::distances_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_msgs::distances_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c99665258f5f578f48a6537226ddf973";
  }

  static const char* value(const ::darknet_ros_msgs::distances_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc99665258f5f578fULL;
  static const uint64_t static_value2 = 0x48a6537226ddf973ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_msgs::distances_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_msgs/distances";
  }

  static const char* value(const ::darknet_ros_msgs::distances_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_msgs::distances_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
distance[] distances\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: darknet_ros_msgs/distance\n\
float64 x\n\
float64 y\n\
float64 z\n\
int64 xmin\n\
int64 ymin\n\
int64 xmax\n\
int64 ymax\n\
";
  }

  static const char* value(const ::darknet_ros_msgs::distances_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_msgs::distances_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distances);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distances_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_msgs::distances_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_msgs::distances_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distances[]" << std::endl;
    for (size_t i = 0; i < v.distances.size(); ++i)
    {
      s << indent << "  distances[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::darknet_ros_msgs::distance_<ContainerAllocator> >::stream(s, indent + "    ", v.distances[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_DISTANCES_H
