// Generated by gencpp from file fuse_all/distance.msg
// DO NOT EDIT!


#ifndef FUSE_ALL_MESSAGE_DISTANCE_H
#define FUSE_ALL_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fuse_all
{
template <class ContainerAllocator>
struct distance_
{
  typedef distance_<ContainerAllocator> Type;

  distance_()
    : dis(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
    }
  distance_(const ContainerAllocator& _alloc)
    : dis(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
  (void)_alloc;
    }



   typedef double _dis_type;
  _dis_type dis;

   typedef int64_t _xmin_type;
  _xmin_type xmin;

   typedef int64_t _ymin_type;
  _ymin_type ymin;

   typedef int64_t _xmax_type;
  _xmax_type xmax;

   typedef int64_t _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::fuse_all::distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fuse_all::distance_<ContainerAllocator> const> ConstPtr;

}; // struct distance_

typedef ::fuse_all::distance_<std::allocator<void> > distance;

typedef boost::shared_ptr< ::fuse_all::distance > distancePtr;
typedef boost::shared_ptr< ::fuse_all::distance const> distanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fuse_all::distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fuse_all::distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fuse_all

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'fuse_all': ['/home/autoware/shared_dir/Project/catkin_ws/src/fuse_all/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fuse_all::distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fuse_all::distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fuse_all::distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fuse_all::distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fuse_all::distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fuse_all::distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fuse_all::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "160e4cc60709095345c6316af60803a5";
  }

  static const char* value(const ::fuse_all::distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x160e4cc607090953ULL;
  static const uint64_t static_value2 = 0x45c6316af60803a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::fuse_all::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fuse_all/distance";
  }

  static const char* value(const ::fuse_all::distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fuse_all::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 dis\n\
int64 xmin\n\
int64 ymin\n\
int64 xmax\n\
int64 ymax\n\
";
  }

  static const char* value(const ::fuse_all::distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fuse_all::distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dis);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fuse_all::distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fuse_all::distance_<ContainerAllocator>& v)
  {
    s << indent << "dis: ";
    Printer<double>::stream(s, indent + "  ", v.dis);
    s << indent << "xmin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUSE_ALL_MESSAGE_DISTANCE_H
